{% set name = "sovapy" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MotokiShiga/sova-cui/archive/v{{ version }}.tar.gz
  sha256: fcbe35227a34a7cf789162afd353ffa9fe803ce030a30f8221390d456712d920

build:
  skip: true  # [py<311 or win]
  script: bash run_install_mac_linux.sh; {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - python
    - setuptools
    - numpy
    - wheel
    - pip
  run:
    - python
    - ase >=3.22.1
    - h5py
    - python-igraph >=0.11.2
    - matplotlib-base
    - networkx >=3.1
    - numpy >=1.23.1
    - tqdm
    - scipy >=1.8
    - spglib >=2.0
    - pycifrw >=4.4.5

test:
  imports:
    - sovapy
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/MotokiShiga/sova-cui
  summary: SOVA (Structural Order Visualization and Analysis) with python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
